version: 0.2

env:
  prameter-store:
    DOCKER_REGISTRY_USERNAME: /codedeploy-webapp/docker/username
    DOCKER_REGISTRY_PASSWORD: /codedeploy-webapp/docker/password

phases:
  pre_build:
    commands:
      - echo "Run Build on Date..."
  build:
    commands:
      - echo "Building Docker Image..."
      - docker build -t "$DOCKER_REGISTRY_USERNAME/codedeploy-webapp:v29aug" .
      - docker images
  post_build:
    commands:
      - echo "Push Image to DockerHub..."
