version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /codedeploy-webapp/docker/username
    DOCKER_REGISTRY_PASSWORD: /codedeploy-webapp/docker/password

phases:
  install:
    commands:
      - echo "Install Apache2..."
      - apt-get update
      - apt-get install apache2 -y
  pre_build:
    commands:
      - echo "Run Build on Date..."
  build:
    commands:
      - echo "Building Docker Image..."
      - docker build -t "$DOCKER_REGISTRY_USERNAME/codedeploy-webapp:v29aug" .
      - docker images
  post_build:
    commands:
      - echo "Push Image to DockerHub..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin docker.io
      - docker push "$DOCKER_REGISTRY_USERNAME/codedeploy-webapp:v29aug"
      - docker logout
      - echo "Image Push to DockerHub Successfully..."

artifacts:
  files:
    - '**/*'
