version: "3.3"
services:
  web1:
    image: "$DOCKER_CREDENTIALS_USR/codedeploy-webapp:v02sep"
    container_name: webappcon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
