version: "3.3"
services:
  web1:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: webappcon
    image: "$DOCKER_CREDENTIALS_USR"/codedeploy-webapp:v02sep
    ports:
      - "80:80"
