version: "3.3"
services:
  web:
    container_name: webappcon
    image: "$DOCKER_CREDENTIALS_USR"/codedeploy-webapp:v02sep 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
